name: Go

on:
  push:
  pull_request:

jobs:
  CI:
    strategy:
      matrix:
        go_version: [ "1.13.x", "1.24.x" ]

    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - name: "Set up Go"
        uses: "actions/setup-go@v5"
        with:
          go-version: ${{ matrix.go_version }}

      - name: "Build"
        run: "go build -v ./..."

      - name: "Test"
        run: "go test -v ./..."

      - name: "Linter"
        uses: "golangci/golangci-lint-action@v7"
        with:
          version: "v2.0"
