name: Go

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  CI:
    strategy:
      matrix:
        go_version: [ "1.18.x", "1.26.x" ]

    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v7"

      - name: "Set up Go"
        uses: "actions/setup-go@v7"
        with:
          go-version: ${{ matrix.go_version }}

      - name: "Build"
        run: "go build -v ./..."

      - name: "Test"
        run: "go test -v ./..."

      - name: "Linter"
        uses: "golangci/golangci-lint-action@v9"
        with:
          version: "latest"

  Coverage:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v7"

      - name: "Set up Go"
        uses: "actions/setup-go@v7"
        with:
          go-version: "1.26.x"

      - name: "Run tests with coverage output"
        run: "go test -race -covermode atomic -coverprofile=covprofile ./..."

      - name: "Install goveralls"
        run: "go install github.com/mattn/goveralls@latest"

      - name: "Send coverage"
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "goveralls -coverprofile=covprofile -service=github"

  Release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v7"

      - name: "Create Release"
        uses: "softprops/action-gh-release@v3"
        with:
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
