name: Go

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  CI:
    strategy:
      matrix:
        go_version: [ "1.18.x", "1.24.x" ]

    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - name: "Set up Go"
        uses: "actions/setup-go@v5"
        with:
          go-version: ${{ matrix.go_version }}

      - name: "Build"
        run: "go build -v ./..."

      - name: "Test"
        run: "go test -v ./..."

      - name: "Linter"
        uses: "golangci/golangci-lint-action@v7"
        with:
          version: "v2.0"

  Release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
